# Generated by Django 5.2 on 2025-12-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('join_date', models.DateField()),
                ('plan_months', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
